/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentUi: typeof import('./src/components/agent-ui/index.vue')['default']
    CouponCard: typeof import('./src/components/coupon-selector/coupon-card.vue')['default']
    CouponSelector: typeof import('./src/components/coupon-selector/index.vue')['default']
    ImageUpload: typeof import('./src/components/agent-ui/image-upload.vue')['default']
    LoginModal: typeof import('./src/components/login-modal.vue')['default']
    MessageList: typeof import('./src/components/agent-ui/message-list.vue')['default']
    NavBar: typeof import('./src/components/nav-bar.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NDivider: typeof import('naive-ui')['NDivider']
    Nfc: typeof import('./src/components/nfc.vue')['default']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NInputGroupLabel: typeof import('naive-ui')['NInputGroupLabel']
    NModal: typeof import('naive-ui')['NModal']
    NPopover: typeof import('naive-ui')['NPopover']
    NSpin: typeof import('naive-ui')['NSpin']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NUpload: typeof import('naive-ui')['NUpload']
    NUploadTrigger: typeof import('naive-ui')['NUploadTrigger']
    RichInput: typeof import('./src/components/agent-ui/rich-input.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StarterPrompts: typeof import('./src/components/agent-ui/starter-prompts.vue')['default']
    UserProfile: typeof import('./src/components/user-profile.vue')['default']
    WaterfallList: typeof import('./src/components/waterfall-list.vue')['default']
  }
}
